version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "56720:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - story_indexer
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch
      - cluster.name=mc_elasticsearch
      - discovery.seed_hosts=elasticsearch,elasticsearch_01,elasticsearch_02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch_01,elasticsearch_02
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - story_indexer
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 2

  elasticsearch_01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch_01
      - cluster.name=mc_elasticsearch
      - discovery.seed_hosts=elasticsearch,elasticsearch_01,elasticsearch_02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch_01,elasticsearch_02
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data_01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - mc_story_indexer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 2

  elasticsearch_02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch_02
      - cluster.name=mc_elasticsearch
      - discovery.seed_hosts=elasticsearch,elasticsearch_01,elasticsearch_02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch_01,elasticsearch_02
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data_02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - mc_story_indexer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  common_worker:
    <<: &common_worker
      build:
        context: ..
        dockerfile: docker/Dockerfile
      environment:
        - RABBITMQ_URL=amqp://rabbitmq:5672
        - RUN=${RUN}
        - RUN_ON_START=1
      networks:
        - story_indexer
      volumes:
        - ../indexer:/app/indexer
      depends_on:
        rabbitmq:
          condition: service_healthy

  fetch_worker:
    <<: *common_worker
    environment:
      - RUN=fetch-worker
    networks:
      - story_indexer

  parser_worker:
    <<: *common_worker
    environment:
      - RUN=parser
    networks:
      - story_indexer

  importer_worker:
    <<: *common_worker
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - story_indexer
    environment:
      - RUN=importer
      - ELASTICSEARCH_HOST=http://elasticsearch:9200,http://elasticsearch_01:9201,http://elasticsearch_02:9202

volumes:
  elasticsearch_data:
  elasticsearch_data_01:
  elasticsearch_data_02:
  rabbitmq_data:

networks:
  story_indexer:
    name: story_indexer
    external: true
