version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mc_story_indexer
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch,elasticsearch_01,elasticsearch_02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch_01,elasticsearch_02
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - mc_story_indexer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 2

  elasticsearch_01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch_01
      - discovery.seed_hosts=elasticsearch,elasticsearch_01,elasticsearch_02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch_01,elasticsearch_02
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data_01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - mc_story_indexer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 2

  elasticsearch_02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - node.name=elasticsearch_02
      - discovery.seed_hosts=elasticsearch,elasticsearch_01,elasticsearch_02
      - cluster.initial_master_nodes=elasticsearch,elasticsearch_01,elasticsearch_02
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data_02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - mc_story_indexer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 2

  common_worker:
    <<: &common_worker
      build:
        context: ..
        dockerfile: docker/Dockerfile
      environment:
        - RABBITMQ_URL=amqp://rabbitmq:5672
        - RUN=${RUN}
      depends_on:
        rabbitmq:
          condition: service_healthy
  fetch_worker:
    <<: *common_worker
    environment:
      - RUN=fetcher

  parser_worker:
    <<: *common_worker
    environment:
      - RUN=parser

  importer_worker:
    <<: *common_worker
    environment:
      - RUN=importer
      - ELASTICSEARCH_HOST=http://elasticsearch:9200,http://elasticsearch_01:9201,http://elasticsearch_02:9202
    networks:
      - mc_story_indexer

volumes:
  elasticsearch_data:
  elasticsearch_data_01:
  elasticsearch_data_02:

networks:
  mc_story_indexer:
    driver: bridge
